### ISSUE TITLE
Neoclipse doesn't show relations between nodes

### ISSUE THREAD

**Issue by chiffa** [neo4j-contrib/neoclipse#48]
I would like to use neoclipse to visualize relations in my neo4j database. However, when I try, only the currently selected node is visible, relations towards the other nodes or other nodes are not visible.

![neoclipse_problem1](https://f.cloud.github.com/assets/1384395/779218/1871d8fa-e9ca-11e2-96c8-da987940b0f9.png)

Stack:
Linux-Ubuntu 13.04 x86-64
Neo4j 1.9, as a service, served on the localhost:7474
neoclipse 1.9

Problem exists, the relations and related nodes are shown in the on-line database explorer:
![noeclipse_problem2](https://f.cloud.github.com/assets/1384395/779219/2052cffc-e9ca-11e2-9c89-a6ca93fee607.png)

Attempted solutions:
- increase/decrease traversal depth
- select relationships with smaller load
- increase maximum traversal depth in options

**Comment by ghost** [comment]
I have the same issue here  with Neoclipse 1.9 on both the Xubuntu 13.04 and WinXP SP3. Can see only one node - no relations, no other nodes...

**Comment by ghost** [comment]
Including logs:

java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getElements(NeoGraphContentProvider.java:133)
    at org.eclipse.zest.core.viewers.internal.GraphModelEntityRelationshipFactory.doBuildGraph(GraphModelEntityRelationshipFactory.java:54)
    at org.eclipse.zest.core.viewers.internal.GraphModelEntityRelationshipFactory.createGraphModel(GraphModelEntityRelationshipFactory.java:43)
    at org.eclipse.zest.core.viewers.internal.AbstractStructuredGraphViewer.inputChanged(AbstractStructuredGraphViewer.java:473)
    at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:280)
    at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1690)
    at org.neo4j.neoclipse.view.NeoGraphViewPart$11.run(NeoGraphViewPart.java:790)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3563)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3212)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.neo4j.neoclipse.Application.start(Application.java:77)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: java.lang.UnsupportedOperationException
    at org.neo4j.rest.graphdb.entity.RestNode.traverse(RestNode.java:109)
    at org.neo4j.neoclipse.graphdb.DefaultTraverser.getNodes(DefaultTraverser.java:77)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getTheElements(NeoGraphContentProvider.java:173)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.access$1(NeoGraphContentProvider.java:146)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:131)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:1)
    at org.neo4j.neoclipse.graphdb.GraphDbServiceManager$TaskWrapper.call(GraphDbServiceManager.java:257)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getElements(NeoGraphContentProvider.java:133)
    at org.eclipse.zest.core.viewers.internal.GraphModelEntityRelationshipFactory.doBuildGraph(GraphModelEntityRelationshipFactory.java:54)
    at org.eclipse.zest.core.viewers.internal.AbstractStylingModelFactory.refreshGraph(AbstractStylingModelFactory.java:305)
    at org.eclipse.zest.core.viewers.internal.AbstractStructuredGraphViewer.internalRefresh(AbstractStructuredGraphViewer.java:323)
    at org.eclipse.jface.viewers.StructuredViewer.internalRefresh(StructuredViewer.java:1299)
    at org.eclipse.jface.viewers.StructuredViewer$8.run(StructuredViewer.java:1535)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1533)
    at org.neo4j.neoclipse.view.NeoGraphViewPart$10.run(NeoGraphViewPart.java:736)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3563)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3212)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.neo4j.neoclipse.Application.start(Application.java:77)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: java.lang.UnsupportedOperationException
    at org.neo4j.rest.graphdb.entity.RestNode.traverse(RestNode.java:109)
    at org.neo4j.neoclipse.graphdb.DefaultTraverser.getNodes(DefaultTraverser.java:77)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getTheElements(NeoGraphContentProvider.java:173)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.access$1(NeoGraphContentProvider.java:146)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:131)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:1)
    at org.neo4j.neoclipse.graphdb.GraphDbServiceManager$TaskWrapper.call(GraphDbServiceManager.java:257)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
    at java.util.concurrent.FutureTask.get(FutureTask.java:111)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getElements(NeoGraphContentProvider.java:133)
    at org.eclipse.zest.core.viewers.internal.GraphModelEntityRelationshipFactory.doBuildGraph(GraphModelEntityRelationshipFactory.java:54)
    at org.eclipse.zest.core.viewers.internal.AbstractStylingModelFactory.refreshGraph(AbstractStylingModelFactory.java:305)
    at org.eclipse.zest.core.viewers.internal.AbstractStructuredGraphViewer.internalRefresh(AbstractStructuredGraphViewer.java:323)
    at org.eclipse.jface.viewers.StructuredViewer.internalRefresh(StructuredViewer.java:1299)
    at org.eclipse.jface.viewers.StructuredViewer$8.run(StructuredViewer.java:1535)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1533)
    at org.neo4j.neoclipse.view.NeoGraphViewPart$10.run(NeoGraphViewPart.java:736)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3563)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3212)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.neo4j.neoclipse.Application.start(Application.java:77)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
Caused by: java.lang.UnsupportedOperationException
    at org.neo4j.rest.graphdb.entity.RestNode.traverse(RestNode.java:109)
    at org.neo4j.neoclipse.graphdb.DefaultTraverser.getNodes(DefaultTraverser.java:77)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.getTheElements(NeoGraphContentProvider.java:173)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider.access$1(NeoGraphContentProvider.java:146)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:131)
    at org.neo4j.neoclipse.view.NeoGraphContentProvider$2.call(NeoGraphContentProvider.java:1)
    at org.neo4j.neoclipse.graphdb.GraphDbServiceManager$TaskWrapper.call(GraphDbServiceManager.java:257)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
