### ISSUE TITLE
neoclipse can't run 

### ISSUE THREAD

**Issue by wangxiaxiao** [neo4j-contrib/neoclipse#57]
Hello Neoclipse team,
I am trying to use eclipse to open the plugin.xml from org.neo4j.neoclipse,but I see the following exception in the console:

INFO: Starting GraphDbServiceManager
!SESSION 2013-12-05 19:11:01.680 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_21
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Framework arguments:  -application org.neo4j.neoclipse.application
Command-line arguments:  -application org.neo4j.neoclipse.application -data C:\Users\ddr\Documents\GitHub/../runtime-org.neo4j.neoclipse.application -dev file:C:/Users/ddr/Documents/GitHub/.metadata/.plugins/org.eclipse.pde.core/org.neo4j.neoclipse.application/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog

!ENTRY org.eclipse.ui 4 0 2013-12-05 19:11:05.124
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
    at org.neo4j.neoclipse.Application.postStartup(Application.java:138)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2707)
    at org.eclipse.ui.internal.Workbench.access$7(Workbench.java:2590)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:608)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.neo4j.neoclipse.Application.start(Application.java:77)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

And there is no problem ,where I export this project into eclipse

Any assistance would be appreciated.

Thanks!

**Comment by sbodese** [comment]
me too, i got the same issue. Well im looking also for a solution

**Comment by CrystalMethod** [comment]
How is the opening of plugin.xml related to the NPE?

**Comment by sbodese** [comment]
Hi Lars,
what do you mean with NPE ? I can open the plugin.xml of the neoclipse project without errors.
But it seems that the neo4j dependency is missed, Tommorrow i try to fix the maven setup. 

eclipse.buildId=unknown
java.version=1.7.0_55
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de
Framework arguments:  -application org.neo4j.neoclipse.application
Command-line arguments:  -application org.neo4j.neoclipse.application -data /Users/sbode/Documents/newLunaWorkspace/../runtime-org.neo4j.neoclipse.application -dev file:/Users/sbode/Documents/newLunaWorkspace/.metadata/.plugins/org.eclipse.pde.core/org.neo4j.neoclipse.application/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 2 0 2014-10-06 17:47:54.042
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-10-06 17:47:54.042
!MESSAGE Bundle initial@reference:file:../../../../../../marumDaten/gits/neoC/org.neo4j.neoclipse/ was not resolved.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.043
!MESSAGE Missing imported package org.neo4j.kernel_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.043
!MESSAGE Missing imported package org.neo4j.graphdb.factory_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.043
!MESSAGE Missing imported package org.json_1.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.043
!MESSAGE Missing imported package org.neo4j.rest.graphdb_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.043
!MESSAGE Missing imported package org.neo4j.graphdb.traversal_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.044
!MESSAGE Missing imported package org.neo4j.rest.graphdb.query_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.044
!MESSAGE Missing imported package org.neo4j.graphdb.index_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.044
!MESSAGE Missing imported package org.neo4j.cypher.javacompat_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.044
!MESSAGE Missing imported package org.neo4j.graphdb.config_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.045
!MESSAGE Missing imported package org.neo4j.graphdb_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.045
!MESSAGE Missing imported package org.neo4j.rest.graphdb.traversal_2.1.4.

!ENTRY org.eclipse.osgi 2 0 2014-10-06 17:47:54.058
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-10-06 17:47:54.058
!MESSAGE Bundle org.neo4j.neoclipse_2.1.4.qualifier [41] was not resolved.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.058
!MESSAGE Missing imported package org.json_1.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.058
!MESSAGE Missing imported package org.neo4j.cypher.javacompat_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.059
!MESSAGE Missing imported package org.neo4j.graphdb_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.059
!MESSAGE Missing imported package org.neo4j.graphdb.config_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.059
!MESSAGE Missing imported package org.neo4j.graphdb.factory_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.059
!MESSAGE Missing imported package org.neo4j.graphdb.index_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.059
!MESSAGE Missing imported package org.neo4j.graphdb.traversal_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.060
!MESSAGE Missing imported package org.neo4j.kernel_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.060
!MESSAGE Missing imported package org.neo4j.rest.graphdb_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.060
!MESSAGE Missing imported package org.neo4j.rest.graphdb.query_2.1.4.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-10-06 17:47:54.060
!MESSAGE Missing imported package org.neo4j.rest.graphdb.traversal_2.1.4.

!ENTRY org.eclipse.osgi 4 0 2014-10-06 17:47:54.061
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.neo4j.neoclipse.application" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error, org.eclipse.ant.core.antRunner.
    at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
    at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)
An error has occurred. See the log file

**Comment by CrystalMethod** [comment]
The stacktrace from @wangxiaxiao lists a NullPointerException, aka NPE. I cannot see any connection between the NPE and "open the plugin.xml". Typicataly one opens the plugin.xml in the development Eclipse but the stacktrace above (as well as your log trace) is from the runtime Eclipse.

**Comment by CrystalMethod** [comment]
Currently the build process contains two steps: a) build the Neo4j OSGi Bundle b) build the Neoclipse Plugins.

You can try to manually add the Neo4j bundle to the Neoclipse Plugin (under lib/ and add that JAR to the MANIFEST.MF) to make Eclipse happy. The problem is, that the Maven/Tycho builds honors Maven dependencies while Eclipse PDE doesnt know how to resolve that dependency.

The right solution would be to add the Neo4j bundle to the target platform.

**Comment by wangxiaxiao** [comment]
think you,I will try more. Any problem,I will ask you,think you very much again 

------------------ 原始邮件 ------------------
发件人: "Lars Martin"notifications@github.com; 
发送时间: 2014年10月8日(星期三) 晚上9:49
收件人: "neo4j-contrib/neoclipse"neoclipse@noreply.github.com; 
抄送: "水晶云"wangxiaxiao2005@qq.com; 
主题: Re: [neoclipse] neoclipse can't run (#57)

Currently the build process contains two steps: a) build the Neo4j OSGi Bundle b) build the Neoclipse Plugins.

You can try to manually add the Neo4j bundle to the Neoclipse Plugin (under lib/ and add that JAR to the MANIFEST.MF) to make Eclipse happy. The problem is, that the Maven/Tycho builds honors Maven dependencies while Eclipse PDE doesnt know how to resolve that dependency.

The right solution would be to add the Neo4j bundle to the target platform.
