### ISSUE TITLE
Failed to start neoclipse from eclipse Indigo

### ISSUE THREAD

**Issue by Pallavim54** [neo4j-contrib/neoclipse#65]
I did mvn -f osgi-bundle/pom.xml install and
mvn install . build success but when i am doing Launch an Eclipse application for plugin.xml its unable to start the neoclipse through eclipse .

I have paste the error getting at the time of doing Launch an Eclipse application for plugin.xml 

!SESSION 2014-06-19 15:13:08.468 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.6.0_26
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_IN
Framework arguments:  -application org.neo4j.neoclipse.application
Command-line arguments:  -application org.neo4j.neoclipse.application -data D:\EclipseWorkspace\19-02-2014\Master/../runtime-org.neo4j.neoclipse.application -dev file:D:/EclipseWorkspace/19-02-2014/Master/.metadata/.plugins/org.eclipse.pde.core/org.neo4j.neoclipse.application/dev.properties -os win32 -ws win32 -arch x86 -consoleLog

!ENTRY org.eclipse.osgi 2 0 2014-06-19 15:13:09.064
!MESSAGE One or more bundles are not resolved because the following root constraints are not resolved:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-19 15:13:09.064
!MESSAGE Bundle initial@reference:file:C:/Users/pmukherjee/Documents/GitHub/folder/neoclipse/org.neo4j.neoclipse/ was not resolved.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.064
!MESSAGE Missing imported package org.neo4j.graphdb.config_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.064
!MESSAGE Missing imported package org.json_1.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.064
!MESSAGE Missing imported package org.dom4j.io_1.6.1.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.rest.graphdb.traversal_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.graphdb.factory_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.graphdb.index_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.graphdb_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.kernel_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.065
!MESSAGE Missing imported package org.neo4j.rest.graphdb.query_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package com.google.gson_[2.1.0,2.2.0).
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package org.dom4j.tree_1.6.1.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package org.neo4j.cypher.javacompat_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package org.neo4j.graphdb.traversal_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package org.neo4j.rest.graphdb_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.066
!MESSAGE Missing imported package org.dom4j_1.6.1.

!ENTRY org.eclipse.osgi 2 0 2014-06-19 15:13:09.071
!MESSAGE The following is a complete list of bundles which are not resolved, see the prior log entry for the root cause if it exists:
!SUBENTRY 1 org.eclipse.osgi 2 0 2014-06-19 15:13:09.071
!MESSAGE Bundle org.neo4j.neoclipse_2.0.0.qualifier [84] was not resolved.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.071
!MESSAGE Missing imported package com.google.gson_[2.1.0,2.2.0).
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.071
!MESSAGE Missing imported package org.dom4j_1.6.1.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.071
!MESSAGE Missing imported package org.dom4j.io_1.6.1.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.071
!MESSAGE Missing imported package org.dom4j.tree_1.6.1.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.json_1.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.cypher.javacompat_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.graphdb_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.graphdb.config_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.graphdb.factory_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.graphdb.index_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.graphdb.traversal_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.kernel_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.072
!MESSAGE Missing imported package org.neo4j.rest.graphdb_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.073
!MESSAGE Missing imported package org.neo4j.rest.graphdb.query_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.073
!MESSAGE Missing imported package org.neo4j.rest.graphdb.traversal_2.0.0.
!SUBENTRY 2 org.neo4j.neoclipse 2 0 2014-06-19 15:13:09.073
!MESSAGE Missing required capability Require-Capability: osgi.ee; filter="(&(osgi.ee=JavaSE)(version=1.7))".

!ENTRY org.eclipse.osgi 4 0 2014-06-19 15:13:09.075
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.neo4j.neoclipse.application" could not be found in the registry. The applications available are: org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error, org.eclipse.ant.core.antRunner.
    at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
    at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by CrystalMethod** [comment]
Neo4j - and thus also Neoclipse - depends on Java 1.7 as the runtime environment. Try to install JRE/JDK 1.7 and make this the default JRE/JDK.
