### ISSUE TITLE
Could not resolve project dependencies

### ISSUE THREAD

**Issue by antonio-castellon** [neo4j-contrib/neoclipse#67]
Dear Developers,

I'm trying to compile the last version from Git hub and I can't find the jar file that defines de dependencies in the reported repositories.... Exists another repository or path where I can find this jar?

Thanks in advance,
Antonio

```
[INFO] Computing target platform for MavenProject: org.neo4j:org.neo4j.neoclipse:2.0.0-SNAPSHOT @ C:\JAVA\Servers\Neo4j\neoclipse\org.neo4j.neoclipse\pom.xml
[WARNING] Missing POM for org.neo4j.neoclipse:org.neo4j.neoclipse.dependencies:jar:2.0.0
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve project dependencies: Missing:
[ERROR] ----------
[ERROR] 1) org.neo4j.neoclipse:org.neo4j.neoclipse.dependencies:jar:2.0.0
[ERROR]
[ERROR] Try downloading the file manually from the project website.
[ERROR]
[ERROR] Then, install it using the command:
[ERROR] mvn install:install-file -DgroupId=org.neo4j.neoclipse -DartifactId=org.neo4j.neoclipse.dependencies -Dversion=2.0.0 -Dpackaging=jar -Dfile=/path/to/file
[ERROR]
[ERROR] Alternatively, if you host your own repository you can deploy the file there:
[ERROR] mvn deploy:deploy-file -DgroupId=org.neo4j.neoclipse -DartifactId=org.neo4j.neoclipse.dependencies -Dversion=2.0.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR] Path to dependency:
[ERROR] 1) org.neo4j:org.neo4j.neoclipse:pom:2.0.0-SNAPSHOT
[ERROR] 2) org.neo4j.neoclipse:org.neo4j.neoclipse.dependencies:jar:2.0.0
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR] org.neo4j:org.neo4j.neoclipse:pom:2.0.0-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR] neo4j-snapshot-repository (http://m2.neo4j.org/content/repositories/snapshots/, releases=false, snapshots=true),
[ERROR] sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR] central (http://repo.maven.apache.org/maven2, releases=true, snapshots=false)

```

**Comment by CrystalMethod** [comment]
This dependency comes from the osgi-bundle project. Simply call

mvn -f osgi-bundle/pom.xml clean install 

before building Neoclipse.

**Comment by antonio-castellon** [comment]
Now it has another issue in the dependencies....

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.neo4j.neoclipse 2.1.4.qualifier
[ERROR]   Missing requirement: org.neo4j.neoclipse.dependencies 2.1.4 requires 'package org.codehaus.jackson.xc 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: org.neo4j.neoclipse 2.1.4.qualifier depends on: package org.json 1.0.0
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.codehaus.jackson.xc 0.0.0.; Unable to satisfy depend
ency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time 0.0.0.; Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time.format 0.0.0.; No solution found because the problem is unsatisfiable.
] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.codehaus.jackson.xc
 0.0.0.; Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time 0.0.0.; Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time.format 0.0.0.; No solution found beca
use the problem is unsatisfiable.]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.codehaus.jackson.xc 0.0.0.; Unable to satisfy dependency from org
.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time 0.0.0.; Unable to satisfy dependency from org.neo4j.neoclipse.dependencies 2.1.4 to package org.joda.time.format 0.0.0.; No solution found because the problem is unsatisfiable.]
        at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
        at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
        at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
        at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
        at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
        at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
        at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        ... 11 m

```

I try to search into all the project where is the declaration about the dependency from jackson and I can't find it!?? ... any ideas?

Thanks in advance
Antonio

**Comment by CrystalMethod** [comment]
Yes, see https://github.com/neo4j-contrib/neoclipse/pull/70

**Comment by antonio-castellon** [comment]
:( the error continues ... I clean and recompile all again and the result is exactly the same exception. :(

**Comment by CrystalMethod** [comment]
You applied the patch from #70 and the error continues? See the Travis-CI build https://travis-ci.org/neo4j-contrib/neoclipse/builds/35411226 of this PR which passed successfully. There must be an error in your local workspace. Do you have a fork of that repo at Github with your local changes?

**Comment by antonio-castellon** [comment]
Thanks a lot, now everything is fine...

**Comment by CrystalMethod** [comment]
Fine, please close the issue if verified.
