### ISSUE TITLE
Neoeclipse db error

### ISSUE THREAD

**Issue by dawn2desk** [neo4j-contrib/neoclipse#72]
Hi, Am using Neo4j 2.1.3 community version. and neoeclipse .19.5. Getting below error while trying to choose database location and connect. Can anybody help on this. 

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.k
ernel.StoreLockerLifecycleAdapter@209fe7' was successfully initialized, but fail
ed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSu
pport.java:497)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:104)
        at org.neo4j.kernel.InternalAbstractGraphDatabase.run(InternalAbstractGr
aphDatabase.java:262)
        ... 8 more
Caused by: org.neo4j.kernel.StoreLockException: Could not create lock file
        at org.neo4j.kernel.StoreLocker.checkLock(StoreLocker.java:74)
        at org.neo4j.kernel.StoreLockerLifecycleAdapter.start(StoreLockerLifecyc
leAdapter.java:40)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSu
pport.java:491)
        ... 10 more

**Comment by CrystalMethod** [comment]
To me it seems that another process (Neo4j Shell, Neo4j Server, ..) already locked the database.

**Comment by JBI1971** [comment]
Hi, 
I am having the same issue... were you able to resolve it?

**Comment by jexp** [comment]
Stop the other process that accesses the database, or use the http connector.
