### ISSUE TITLE
Support of remote db location

### ISSUE THREAD

**Issue by nrkkalyan** [neo4j-contrib/neoclipse#8]
Need to integrate support for remote db locations. like http://localhost:7474/test.db etc..

**Comment by jexp** [comment]
could use the java-rest-graphdb wrapper to access the server

**Comment by peterneubauer** [comment]
Cool,
you could just use the RESTGraphDatabase for that I guess,
https://github.com/neo4j/java-rest-binding

/peter

On Wed, Dec 21, 2011 at 4:09 PM, Radhakrishna Kalyan
reply@reply.github.com
wrote:

**Comment by nrkkalyan** [comment]
When I am using 
GraphDatabaseService gds = new RestGraphDatabase( "http://localhost:7474/db/data" );

I am getting exception. Any idea...

Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: C:\Kalyan\github\nrkkalyan\workspace\Test\http:\localhost:7474\db\data\messages.log (The filename, directory name, or volume label syntax is incorrect)
    at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.<init>(StringLogger.java:101)
    at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.<init>(StringLogger.java:81)
    at org.neo4j.kernel.impl.util.StringLogger.logger(StringLogger.java:44)
    at org.neo4j.kernel.impl.util.StringLogger.logger(StringLogger.java:39)
    at org.neo4j.kernel.AbstractGraphDatabase.createStringLogger(AbstractGraphDatabase.java:49)
    at org.neo4j.kernel.AbstractGraphDatabase.<init>(AbstractGraphDatabase.java:44)
    at org.neo4j.rest.graphdb.AbstractRemoteDatabase.<init>(AbstractRemoteDatabase.java:64)
    at org.neo4j.rest.graphdb.RestGraphDatabase.<init>(RestGraphDatabase.java:35)
    at org.neo4j.rest.graphdb.RestGraphDatabase.<init>(RestGraphDatabase.java:48)
    at org.neo4j.rest.graphdb.RestGraphDatabase.<init>(RestGraphDatabase.java:40)
    at XYZ.main(XYZ.java:32)
Caused by: java.io.FileNotFoundException: C:\Kalyan\github\nrkkalyan\workspace\Test\http:\localhost:7474\db\data\messages.log (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.openAppend(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:192)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.instantiateWriter(StringLogger.java:114)
    at org.neo4j.kernel.impl.util.StringLogger$ActualStringLogger.<init>(StringLogger.java:97)
    ... 10 more

**Comment by jexp** [comment]
thats an issue with the update to 1.6

will look into it today

mobile mail please excuse brevity and typos

Am 23.12.2011 um 03:04 schrieb Radhakrishna Kalyan reply@reply.github.com:

**Comment by jexp** [comment]
Please try it with the currently relased version 1.6.M02 there this problem should be gone.

**Comment by nrkkalyan** [comment]
Hi,

I tried M02, but still the same problem . Can you please let me know if we have any example using java-rest-graphdb

**Comment by jexp** [comment]
Not neo4j 1.6.M02 but java-rest-graphdb 1.6.M02

**Comment by nrkkalyan** [comment]
Perfect, its working now.
